name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: check the environment
      run: g++ --version && git --version && bash --version
      run: cmake --version
    - name: make the project
      run: |
        mkdir build
        pushd build
        cmake ..
        make
        popd
    - name: test
      run: |
        pushd build
        make test
        popd
    - name: test with bash
      run: |
        ./build/tests/test_pt_os
        echo "DONE
        "
