name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: check the environment
      run: g++ --version && git --version && bash --version
    - name: list the environment
      run: ls -la
    - name: build with bash
      run: bash bash_build.sh
    - name: run tests
      run: |
        pushd build
        ./test_pt_os
        popd
