name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check the environment
      run: g++ --version && git --version && bash --version
    - name: build with bash
      run: bash bash_build.sh
    - name: run tests
      run: pushd build && ./test_pt_os &&popd
